# Generated by Django 3.0.8 on 2020-07-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='listed_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='listed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
